### ISSUE TITLE
Confusing methods/properties in API

### ISSUE THREAD

**Issue by nonsensery** [Electrode-iOS/ELReachability#4]
The public API for `ELReachability` consists of two types: `NetworkStatus`, and `NetworkStatusInterpreter`. The former exposes reachability state through methods, like `networkStatus.isReachable()` and the latter does it through computed properties, like `networkStatusInterpreter.isReachable`. This is kind of confusing.

FWIW, I'd rather have `NetworkStatusInterpreter` replaced with an `enum`, like:

``` swift
public enum Reachability {
    case Offline, Cellular, WiFi
}

public typealias NetworkStatusCallbackClosure = (reachability: Reachability) -> Void

public class NetworkStatus {
    var currentReachability: Reachability { … }
}
```

**Comment by angelodipaolo** [comment]
I agree about it being confusing and that an enum would be a better fit. Since this would be a breaking API change I'd like to see it land in the next major version, which would also support Swift 3.

@nonsensery Is this something you are interested in implementing? If not I can find time in the next week to get this change in as part of the [updates for Swift 3](https://github.com/Electrode-iOS/ELReachability/pull/5).

**Comment by nonsensery** [comment]
@angelodipaolo Yeah, sure. I can take a look today.

**Comment by angelodipaolo** [comment]
Fixed via https://github.com/Electrode-iOS/ELReachability/pull/6/commits/37be9aa081d393037ccc7a63ea95e6b00909db00
